# NumPy ufuncs

In [2]:
import numpy as np

## What are ufuncs?
#### ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.

## Why use ufuncs?
#### ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
#### They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

# What is Vectorization?
#### Converting iterative statements into a vector based operation is called vectorization.
#### It is faster as modern CPUs are optimized for such operations.

# Simple Arithmetic

### Addition


In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])

newarr = np.add(arr1, arr2)
print(arr1, "+", arr2, "\n=", newarr)


[1 2 3 4 5] + [1 2 3 4 5] 
= [ 2  4  6  8 10]


### Subtraction

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 6])

newarr = np.subtract(arr1, arr2)
print(arr1, "-", arr2, "\n=", newarr)


[1 2 3 4 5] - [1 2 3 4 6] 
= [ 0  0  0  0 -1]


### Multiplication

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 6])

newarr = np.multiply(arr1, arr2)
print(arr1, "*", arr2, "\n=", newarr)


[1 2 3 4 5] * [1 2 3 4 6] 
= [ 1  4  9 16 30]


### Division

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 6])

newarr = np.divide(arr1, arr2)
print(arr1, "\\", arr2, "\n=", newarr)


[1 2 3 4 5] \ [1 2 3 4 6] 
= [1.         1.         1.         1.         0.83333333]


### Power

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 2, 2, 2, 2])

newarr = np.power(arr1, arr2)
print(arr1, "^", arr2, "\n=", newarr)


[1 2 3 4 5] ^ [2 2 2 2 2] 
= [ 1  4  9 16 25]


### Remainder 


In [8]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 2, 2, 2, 2])

newarr = np.mod(arr1, arr2)
print(arr1, "%", arr2, "\n=", newarr)

[1 2 3 4 5] % [2 2 2 2 2] 
= [1 0 1 0 1]
