# NumPy Tutorial
#### NumPy is a Python library.
#### NumPy is used for working with arrays.
#### NumPy is short for "Numerical Python".

# why use numpy?
### In Python we have lists that serve the purpose of arrays, but they are slow to process.
### Numpy aims to provide an array object that is up to 50x faster than traditional Python lists.
### The array object in Numpy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
### Arrays are very frequently used in data science, where speed and resources are very important.

In [2]:
import numpy as np


In [3]:
# Initializing 1d array of size 5 with 0
initializing_1Darray = np.zeros([5])
print(initializing_1Darray)


[0. 0. 0. 0. 0.]


In [4]:
# Initializing 2d array of size 3X3 with 0
initializing_2Darray = np.zeros([3, 3])
print(initializing_2Darray)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# np.ones([size1, size2]) : initialize array of specified size with 1's
x = np.ones([3, 3])
print(x)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [74]:
# To generate array with in specified limit
#x = np.arange(start , stop(not included), step, dtype=i4)
x = np.arange(1, 11, 1, dtype='i4')
print(f"array1 = {x}")

y = np.arange(10, 0, -1)
print(f"array2 = {y}")


array1 = [ 1  2  3  4  5  6  7  8  9 10]
array2 = [10  9  8  7  6  5  4  3  2  1]


In [7]:
# Generating 20 numbers between 1 to 10
x = np.linspace(1, 10, 20)
print(x)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [8]:
# Generating 8 numbers(10^2,10^3,10^4,10^5...) between 2 to 4
x = np.logspace(2, 4, 8)
print(x)


[  100.           193.06977289   372.75937203   719.685673
  1389.49549437  2682.69579528  5179.47467923 10000.        ]


# Generating random number in nd array

In [9]:
x = np.random.rand()
print(x)

0.07865563916085816


In [10]:
y = np.random.rand(10)
print(y)


[0.26743498 0.13588083 0.60368474 0.43753323 0.1004424  0.91577178
 0.83385001 0.05971234 0.46696217 0.62642164]


In [11]:
z = np.random.rand(2, 2)
print(z)


[[0.15593653 0.07421824]
 [0.44969189 0.92761382]]


In [12]:
n = np.random.rand(2, 2, 2)
print(n)


[[[0.10807353 0.26476765]
  [0.42450568 0.19574645]]

 [[0.73601497 0.95415444]
  [0.55058111 0.89209112]]]


In [92]:
# Generating number between 0 to 10
x = np.random.randint(10)
print(x)

9


In [13]:
# Generating number between 0 to 10 in array 5X5
x = np.random.randint(0, 10, size=(5, 5))
print(x)


[[3 1 6 0 7]
 [7 5 3 4 6]
 [1 4 5 8 1]
 [7 0 5 0 0]
 [9 2 9 6 0]]


In [14]:
# Genarting 3X3 matrix filled with 5
x = np.full((3, 3), 5)
print(x)


[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
# Create a new array by repeating an existing array for a particular number of times
arr = np.array([1, 2, 3, 4, 5])
x = np.tile(arr, 5)
print(x)


[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [16]:
# print(np.info(max))
# to know about the particular function in numpy

# print(np.info(np.arange))
print(np.info(np.array))
# print(np.info(np.sum))


array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) 

# N-D Array


In [17]:
# Creating 0-D Array
x = np.array(10)
print(x)
print("dimension of array : ", x.ndim)


10
dimension of array :  0


In [18]:
# Creeating 1-D Array
y = np.array([1, 2, 3, 4, 5])
print(y)
print("dimension of array : ", y.ndim)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[1 2 3 4 5]
dimension of array :  1
[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [19]:
# Creeating 2-D Array
z = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
print(z)
print("dimension of array : ", z.ndim)


[[1 2 3 4 5]
 [6 7 8 9 0]]
dimension of array :  2


In [20]:
# Creeating 3-D Array
n = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [1, 2, 4]]
])
print(n)
print("dimension of array : ", n.ndim)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 4]]]
dimension of array :  3


# Numpy Array Indexing And Slicing

In [21]:
# In 1-D Array:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Indexing
print(y[0])
print(y[9])

# Slicing
print(y[0:4])
print(y[0:11:2])
print(y[::])
print(y[10:1:-2])


1
10
[1 2 3 4]
[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10]
[10  8  6  4]


In [22]:
# In 2-D Array
z = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("INDEXING : ")
print(z[0, 0], end=" ")
print(z[0, 1], end=" ")
print(z[0, 2], end=" ")
print(z[1, 3], end=" ")
print(z[1, 4], end="\n")

print("SLICING : ")
print(z[0, 0:6])
print(z[1, 0:6])

print("Note This: ")
print(z[0:2, 0:3])
print(z[0:2, 0:6:2])


INDEXING : 
1 2 3 9 10
SLICING : 
[1 2 3 4 5]
[ 6  7  8  9 10]
Note This: 
[[1 2 3]
 [6 7 8]]
[[ 1  3  5]
 [ 6  8 10]]


In [23]:
# In 3-D Array:
z = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("INDEXING : ")
print(z[0, 0, 1], end=" ")
print(z[0, 0, 2], end=" ")
print(z[0, 1, 1], end=" ")
print(z[0, 1, 2], end=" ")
print(z[1, 0, 1], end=" ")
print(z[1, 0, 2], end=" ")
print(z[1, 1, 1], end=" ")
print(z[1, 1, 2], end="\n")

print("SLICING : ")
print(z[0, 0, 0:2])
print(z[1, 0, 0:2])

print("INDEXING : ")
print("Note this: ")
print(z[0:2, 1, 0:2])
print("Note this: ")
print(z[0:2, 0, 0:2])
print("Note this: ")
print(z[0:2, 0:2, 0:2])


INDEXING : 
2 3 5 6 8 9 11 12
SLICING : 
[1 2]
[7 8]
INDEXING : 
Note this: 
[[ 4  5]
 [10 11]]
Note this: 
[[1 2]
 [7 8]]
Note this: 
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


# Numpy Datatypes
### NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
### i - integer
### b - boolean
### u - unsigned integer
### f - float
### c - complex float
### m - timedelta
### M - datetime
### O - object
### S - string
### U - unicode string
### V - fixed chunk of memory for other type ( void )


In [24]:
x = np.array([1, 2, 3, 4, 5])
print(x)
print("Datatype of array:", x.dtype)


[1 2 3 4 5]
Datatype of array: int32


In [25]:
# in i4, 4 is the size specified
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype="i4")
print(arr, "\n", arr.dtype)


[[1 2 3]
 [4 5 6]] 
 int32


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype="S")
print(arr, "\n", arr.dtype)


[[b'1' b'2' b'3']
 [b'4' b'5' b'6']] 
 |S1


In [27]:
# Number >=1 and <0 is True
# Number = 0 is False
arr = np.array([[-1, 2, -3], [4, 0, 0]], dtype="bool")
print(arr, "\n", arr.dtype)


[[ True  True  True]
 [ True False False]] 
 bool


In [28]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, ":", arr.dtype)

# copy and convert datatype of existing array to new_array

new_arr = arr.astype(bool)
print(new_arr, ":", new_arr.dtype)

new_arr1 = arr.astype("S")
print(new_arr1, ":", new_arr1.dtype)


[1 2 3 4 5] : int32
[ True  True  True  True  True] : bool
[b'1' b'2' b'3' b'4' b'5'] : |S11


# Array Copy Vs Array View

### The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

### The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr, "Dimension:", arr.ndim, "DataType: ", arr.dtype)
print(arr.base)


print("copy() : ")
newarr = arr.copy()
print(newarr, "Dimension:", newarr.ndim, "DataType: ", newarr.dtype)

# changes in newarr will not affect the actual arr
newarr[0, 2] = 100
print("New_Array:", newarr)
print("Actual_Array:", arr)

# arr.base() : return array own by array. if it takes a copy of anouther array then it will show None as output
print(newarr.base)


[[1 2 3 4]
 [5 6 7 8]] Dimension: 2 DataType:  int32
None
copy() : 
[[1 2 3 4]
 [5 6 7 8]] Dimension: 2 DataType:  int32
New_Array: [[  1   2 100   4]
 [  5   6   7   8]]
Actual_Array: [[1 2 3 4]
 [5 6 7 8]]
None


In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr, "Dimension:", arr.ndim, "DataType: ", arr.dtype)

print("view() : ")
newarr = arr.view()
print(newarr, "Dimension:", newarr.ndim, "DataType: ", newarr.dtype)

# changes in newarr will  affect the actual arr
newarr[0, 2] = 100
print("New_Array:", newarr)
print("Actual_Array:", arr)

# arr.base() : return array own by array. if it takes a copy of anouther array then it will show None as output
print(newarr.base)


[[1 2 3 4]
 [5 6 7 8]] Dimension: 2 DataType:  int32
view() : 
[[1 2 3 4]
 [5 6 7 8]] Dimension: 2 DataType:  int32
New_Array: [[  1   2 100   4]
 [  5   6   7   8]]
Actual_Array: [[  1   2 100   4]
 [  5   6   7   8]]
[[  1   2 100   4]
 [  5   6   7   8]]


# Numpy Array Shaping
## The shape of an array is the number of elements in each dimension.
## NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [31]:
# To print Shape Of The Array:
# arr.shape: o/p:(row,col): (1,2) or (1,2,3) etc

arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr1.shape)

arr2 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(arr2.shape)

arr3 = np.array([1, 2, 3, 4], ndmin=5)
print(arr3.shape)


(5,)
(2, 5)
(2, 2, 3)
(1, 1, 1, 1, 4)


In [93]:
# Itemsize returns the size (in bytes) of each element of a Numpy array.
arr = np.array([1, 2, 3, 4, 5])
print(arr.itemsize)

arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr1.itemsize)

arr2 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(arr2.itemsize)

arr3 = np.array([1, 2, 3, 4], ndmin=5)
print(arr3.itemsize)

4
4
4
4


# Numpy Array ReShapping
## Reshaping means changing the shape of an array.
## The shape of an array is the number of elements in each dimension.
## By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)


newarr = arr.reshape(2, 3)
# as (2,3) means total 6 element must be there in existing array
print(newarr)

try:
    newarr = arr.reshape(4, 2)
except:
    print("""ERROR: As (4,2) means total 8 element must be there in existing array
    But there is only 6 elements in existing array """)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
ERROR: As (4,2) means total 8 element must be there in existing array
    But there is only 6 elements in existing array 


## Unknown Dimension

### You are allowed to have one "unknown" dimension.
### Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
### Pass -1 as the value, and NumPy will calculate this number for you.

In [33]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])
print(arr.reshape(2, 3, 2))
print("Unknown Dimensions : ")
print(arr.reshape(1, 4, -1))

# Reshape to 1-D Array
print(arr.reshape(-1))


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Unknown Dimensions : 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# NumPy Array Iterating
## Iterating means going through elements one by one.
## As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

In [34]:
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Elements By Elements: ")
for i in arr1d:
    print(i, end=" ")


Elements By Elements: 
1 2 3 4 5 6 7 8 9 

In [35]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Elements By Elements: ")
for i in arr2d:
    for j in i:
        print(j, end=" ")
print("\nPrinting 1DArrays in 2DArray;")
for i in arr2d:
    print(i)


Elements By Elements: 
1 2 3 4 5 6 7 8 
Printing 1DArrays in 2DArray;
[1 2 3 4]
[5 6 7 8]


In [36]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])

print("Printing Elements By Elements: ")
for i in arr3d:
    for j in i:
        for k in j:
            print(k, end=" ")

print("\nprinting 2darrays in 3Darray: ")
for i in arr3d:
    print(i)

print("printing 1darrays in 2darrays of 3Darray: ")
for i in arr3d:
    for j in i:
        print(j)


Printing Elements By Elements: 
1 2 3 4 5 6 7 8 9 10 11 12 
printing 2darrays in 3Darray: 
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
printing 1darrays in 2darrays of 3Darray: 
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


## Iterating Arrays Using nditer()
### The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

In [37]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i in np.nditer(arr2d):
    print(i, end=" ")


1 2 3 4 5 6 7 8 

In [38]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i in np.nditer(arr2d[0, 0:4]):
    print(i, end=" ")


1 2 3 4 

In [39]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i in np.nditer(arr2d[0:2, 0:3]):
    print(i, end=" ")


1 2 3 5 6 7 

In [40]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])
for i in np.nditer(arr3d):
    print(i, end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 

In [41]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])
for i in np.nditer(arr3d[0:2, 0:2, 0:2]):
    print(i, end=" ")


1 2 4 5 7 8 10 11 

## Enumerated Iteration Using ndenumerate()
### Enumeration means mentioning sequence number of somethings one by one.
### Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [42]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for index, i in np.ndenumerate(arr2d):
    print(index, ":", i)


(0, 0) : 1
(0, 1) : 2
(0, 2) : 3
(0, 3) : 4
(1, 0) : 5
(1, 1) : 6
(1, 2) : 7
(1, 3) : 8


In [43]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for index, i in np.ndenumerate(arr2d[0:2, 0:3]):
    print(index, ":", i)


(0, 0) : 1
(0, 1) : 2
(0, 2) : 3
(1, 0) : 5
(1, 1) : 6
(1, 2) : 7


In [44]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])
for index, i in np.ndenumerate(arr3d):
    print(index, ":", i)


(0, 0, 0) : 1
(0, 0, 1) : 2
(0, 0, 2) : 3
(0, 1, 0) : 4
(0, 1, 1) : 5
(0, 1, 2) : 6
(1, 0, 0) : 7
(1, 0, 1) : 8
(1, 0, 2) : 9
(1, 1, 0) : 10
(1, 1, 1) : 11
(1, 1, 2) : 12


In [45]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
])
for index, i in np.ndenumerate(arr3d[0:2, 0:2, 0:2]):
    print(index, ":", i)


(0, 0, 0) : 1
(0, 0, 1) : 2
(0, 1, 0) : 4
(0, 1, 1) : 5
(1, 0, 0) : 7
(1, 0, 1) : 8
(1, 1, 0) : 10
(1, 1, 1) : 11


# NumPy Joining Array
## Joining means putting contents of two or more arrays in a single array.
## We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [46]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

newarr = np.concatenate((arr1, arr2))
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10]


In [47]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

newarr = np.concatenate((arr1, arr2), axis=0)  # axis = 0 is By Default
print(newarr)


[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
arr1 = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])
arr2 = np.array([[6, 7, 8, 9, 10], [60, 70, 80, 99, 100]])

newarr = np.concatenate((arr1, arr2), axis=0)
print(newarr)


[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [  6   7   8   9  10]
 [ 60  70  80  99 100]]


In [49]:
arr1 = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])
arr2 = np.array([[6, 7, 8, 9, 10], [60, 70, 80, 99, 100]])

newarr = np.concatenate((arr1, arr2), axis=1)
print(newarr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  99 100]]


## Joining Arrays Using Stack Functions
### Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

### We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

### We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [50]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
x = np.hstack((arr1, arr2))  # Horizontal Joining
y = np.vstack((arr1, arr2))  # Vertical joining

print(arr)
print(x)
print(y)


[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Splitting NumPy Arrays
### Splitting is reverse operation of Joining.

### Joining merges multiple arrays into one and Splitting breaks one array into multiple.

### We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6])
# Split the array into 3 equal parts and return list of arrays
newarr = np.array_split(arr, 3)
print(newarr)

for i in newarr:
    print(i)

print("Elements By Elements:")
for i in newarr:
    for j in i:
        print(j, end=" ")


[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
Elements By Elements:
1 2 3 4 5 6 

In [52]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
newarr = np.array_split(arr, 3)
print(newarr)

print("Arrays Generated: ")
for i in newarr:
    print(i)

# for i in newarr:
#     for j in i:
#         print(j)


[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int32)]
Arrays Generated: 
[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[]


In [53]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
newarr = np.array_split(arr, 2, axis=1)
print(newarr)

print("Arrays Generated: ")
for i in newarr:
    print(i)


[array([[1, 2, 3],
       [6, 7, 8]]), array([[ 4,  5],
       [ 9, 10]])]
Arrays Generated: 
[[1 2 3]
 [6 7 8]]
[[ 4  5]
 [ 9 10]]


In [54]:
arr = np.array([
    [1, 2, 3],
    [6, 7, 8],
    [11, 12, 13]
])
newarr = np.hsplit(arr, 3)
print("Horizontal Split: ", newarr)
print("Arrays Generated using Horizontal Split:")
for i in newarr:
    print(i)

newarr = np.vsplit(arr, 3)
print("Vertical Split: ", newarr)
print("Arrays Generated using Vertical Split:")
for i in newarr:
    print(i)


Horizontal Split:  [array([[ 1],
       [ 6],
       [11]]), array([[ 2],
       [ 7],
       [12]]), array([[ 3],
       [ 8],
       [13]])]
Arrays Generated using Horizontal Split:
[[ 1]
 [ 6]
 [11]]
[[ 2]
 [ 7]
 [12]]
[[ 3]
 [ 8]
 [13]]
Vertical Split:  [array([[1, 2, 3]]), array([[6, 7, 8]]), array([[11, 12, 13]])]
Arrays Generated using Vertical Split:
[[1 2 3]]
[[6 7 8]]
[[11 12 13]]


# NumPy Searching Arrays
### You can search an array for a certain value, and return the indexes that get a match.

### To search an array, use the where() method.

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = np.where(arr == 10)
print(x)


(array([9], dtype=int64),)


In [56]:
arr = np.array([1, 2, 3, 4, 5, 1, 6, 4, 7, 4, 8, 4])
indexes = np.where(arr == 4)
print(indexes)

for i in indexes:
    for j in i:
        print("Element Found At ", j)


(array([ 3,  7,  9, 11], dtype=int64),)
Element Found At  3
Element Found At  7
Element Found At  9
Element Found At  11


In [57]:
arr = np.array([1, 2, 3, 4, 5, 1, 6, 4, 7, 4, 8, 4])
# Find the Indexes where elements are even
find = np.where(arr % 2 == 0)
print(find)


(array([ 1,  3,  6,  7,  9, 10, 11], dtype=int64),)


In [58]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
index = np.where(arr == 10)
print(index)

for i in index:
    print(i, end=" ")


(array([1], dtype=int64), array([4], dtype=int64))
[1] [4] 

# Search Sorted
### There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.searchsorted(arr, 3)
print(x)


2


In [60]:
arr = np.array([1, 2, 7, 4, 5, 6])
x = np.searchsorted(arr, 3)
print(x)


2


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.searchsorted(arr, 3100)
print(x)


6


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.searchsorted(arr, 3, side='right')
print(x)


3


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.searchsorted(arr, 300, side='right')
print(x)


6


In [64]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
# position of elements will get return in array
print(x)


[1 2 3]


# NumPy Sorting Arrays
### Sorting means putting elements in an ordered sequence.

### Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

### The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [65]:
arr = np.array([30, 20, 4, 5, 7, 8, 0])
print(np.sort(arr))


[ 0  4  5  7  8 20 30]


In [66]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [67]:
arr = np.array([True, False, True])
print(np.sort(arr))


[False  True  True]


In [68]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


# NumPy Filter Array
### Getting some elements out of an existing array and creating a new array out of them is called filtering.

### In NumPy, you filter an array using a boolean index list.

### "A boolean index list is a list of booleans corresponding to indexes in the array."

##### If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("Array: ", arr)
x = [True, False, True, False, True, False, True]
newarr = arr[x]
print("Filtered Array", newarr)


Array:  [1 2 3 4 5 6 7]
Filtered Array [1 3 5 7]


In [70]:
arr = np.array([40, 42, 39, 45, 50, 20, 11, 67, 89, 90])
print("Array : ", arr)
filterarr = []

for i in arr:
    if(i >= 40):
        filterarr.append(True)
    else:
        filterarr.append(False)

newarr = arr[filterarr]
print("Filtered_Array: ", newarr)


Array :  [40 42 39 45 50 20 11 67 89 90]
Filtered_Array:  [40 42 45 50 67 89 90]


### Creating Filter Directly From Array
##### We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array : ", arr)
filterarr = arr > 5
newarr = arr[filterarr]

print(filterarr)
print("Filtered_Array: ", newarr)


Array :  [ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
Filtered_Array:  [ 6  7  8  9 10]


In [72]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array : ", arr)
filter_arr = arr % 2 == 0
newarr = arr[filterarr]

print(filterarr)
print("Filtered_Array: ", newarr)


Array :  [ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
Filtered_Array:  [ 6  7  8  9 10]
