<br>
<div align="center">
    <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="NumPy">
</div>
<br>

# `NumPy` stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements. `Travis Oliphant` created NumPy package in 2005 by injecting the features of the ancestor module Numeric into another module Numarray.

# It is an extension module of Python which is mostly written in C. It provides various functions which are capable of performing the numeric computations with a high speed.

In [6]:
# importing numpy library with alias name as np
import numpy as np


# Creating Arrays in NumPy
## NumPy Ndarray : np.array()
The array object in NumPy is called ndarray

### Parameters of np.array()
| SN  | Parameter | Description                                                                                                                                      |
| --- | --------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| 1   | object    | It represents the collection object. It can be a list, tuple, dictionary, set, etc.                                                              |
| 2   | dtype     | We can change the data type of the array elements by changing this option to the specified type. The default is none.                            |
| 3   | copy      | It is optional. By default, it is true which means the object is copied.                                                                         |
| 4   | order     | There can be 3 possible values assigned to this option. It can be C (column order), R (row order), or A (any)                                    |
| 5   | subok     | The returned array will be base class array by default. We can change this to make the subclasses passes through by setting this option to true. |
| 6   | ndmin     | It represents the minimum dimensions of the resultant array.                                                                                     |

In [10]:
# np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

arr0D = np.array(1)
arr1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
arr2D = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("0-D array :", arr0D)
print("1-D array :", arr1D)
print("2-D array :", arr2D)
print("3-D array :", arr3D)


0-D array : 1
1-D array : [1 2 3 4 5 6 7 8 9 0]
2-D array : [[1 2 3 4 5]
 [6 7 8 9 0]]
3-D array : [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Check number of Dimensions : ndim

In [11]:
print(" dimension of array: ", arr0D.ndim)
print(" dimension of array: ", arr1D.ndim)
print(" dimension of array: ", arr2D.ndim)
print(" dimension of array: ", arr3D.ndim)


 dimension of array:  0
 dimension of array:  1
 dimension of array:  2
 dimension of array:  3


### Higher Dimensional Arrays

In [14]:
array = np.array([1, 2, 3], ndmin=5)
print(array)
print(" dimension of array: ", array.ndim)


[[[[[1 2 3]]]]]
 dimension of array:  5


## np.empty() , np.zeros() , np.ones()

### parameters.
- Shape: The desired shape of the specified array.
- dtype: The data type of the array items. The default is the float.
- Order: The default order is the c-style row-major order. It can be set to F for FORTRAN-style column-major order.

In [24]:
emptArray = np.empty((3,2),dtype = int)
print(emptArray)

[[2035874288        525]
 [         0          0]
 [         1          0]]


In [27]:
emptArray = np.empty((3,5),dtype = float)
print(emptArray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
zeroArray = np.zeros((3, 3), dtype=float)
print(zeroArray)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
oneArray = np.ones((3,2), dtype=float)
print(oneArray)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
